# Generated by Django 2.1.7 on 2020-07-06 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20200706_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(blank=True, max_length=200)),
                ('Department', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('varification_id', models.IntegerField(default=1245)),
                ('varified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
